advancementMap:
  "nether/create_full_beacon": "Beaconator"
  "nether/all_effects": "How Did We Get Here?"
  "end/kill_dragon": "Free the End"
  "end/dragon_egg": "The Next Generation"
  "end/enter_end_gateway": "Remote Getaway"
  "end/respawn_dragon": "The End... Again..."
  "end/dragon_breath": "You Need a Mint"
  "end/find_end_city": "The City at the End of the Game"
  "end/elytra": "Sky's the Limit"
  "end/levitate": "Great View From Up Here"
  "adventure/voluntary_exile": "Voluntary Exile"
  "adventure/kill_a_mob": "Monster Hunter"
  "adventure/trade": "What a Deal!"
  "adventure/honey_block_slide": "Sticky Situation"
  "adventure/ol_betsy": "Ol' Betsy"
  "adventure/sleep_in_bed": "Sweet Dreams"
  "adventure/hero_of_the_village": "Hero of the Village"
  "adventure/throw_tident": "Throwaway Joke"
  "adventure/shoot_arrow": "Take Aim"
  "adventure/kill_all_mobs": "Monsters Hunted"
  "adventure/totem_of_undying": "Postmortal"
  "adventure/summon_iron_golem": "Hired Help"
  "adventure/two_birds_one_arrow": "Two Birds, One Arrow"
  "adventure/whos_the_pillager_now": "Who's the Pillager Now?"
  "adventure/arbalistic": "Arbalistic"
  "adventure/adventuring_time": "Adeventuring Time"
  "adventure/very_very_frightening": "Very Very Frightening"
  "adventure/sniper_duel": "Sniper Duel"
  "adventure/bullseye": "Bullseye"
  "husbandry/safely_harvest_honey": "Bee Our Guest"
  "husbandry/breed_an_animal": "The Parrots and the Bats"
  "husbandry/tame_an_animal": "Best Friends Forever"
  "husbandry/fishy_business": "Fishy Business"
  "husbandry/silk_touch_nest": "Total Beelocation"
  "husbandry/plant_seed": "A Seedy Place"
  "husbandry/breed_all_animals": "Two by Two"
  "husbandry/complete_catalogue": "A Complete Catalogue"
  "husbandry/tactical_fishing": "Tactial Fishing"
  "husbandry/balanced_diet": "A Balanced Diet"
  "husbandry/obtain_netherite_hoe": "Serious Dedication"
  "husbandry/allay_deliver_cake_to_note_block": "Birthday Song"
  "husbandry/tadpole_in_a_bucket": "Bukkit Bukkit"
  "adventure/kill_mob_near_sculk_catalyst": "It Spreads"
  "adventure/avoid_vibration": "Sneak 100"
  "husbandry/leash_all_frog_variants": "When the Squad Hops into Town"
  "husbandry/froglights": "With Our Powers Combined!"
  "husbandry/allay_deliver_item_to_player": "You've Got a Friend in Me"